services:
  greact-parking:
    build: .
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true  # Здесь external: true, так как сеть создана в другом стеке
